In [4]:
import numpy as np

x = np.arange(4)
y = np.ones((3, 4))
print(x.shape)  # (4,)
print(y.shape)  # (3, 4)

print((x + y).shape)  # (3, 4)
print(x + y)
# [[1. 2. 3. 4.]
#  [1. 2. 3. 4.]
#  [1. 2. 3. 4.]]

(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [5]:
x = np.arange(4).reshape(4, 1)
y = np.ones(5)

print(x.shape)  # (4, 1)
print(y.shape)  # (5,)

print((x + y).shape)  # (4, 5)
print(x + y)
# [[1. 1. 1. 1. 1.]
#  [2. 2. 2. 2. 2.]
#  [3. 3. 3. 3. 3.]
#  [4. 4. 4. 4. 4.]]

x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])
z = x[:, np.newaxis] + y
print(z)
# [[ 1.  2.  3.]
#  [11. 12. 13.]
#  [21. 22. 23.]
#  [31. 32. 33.]]

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [6]:
x = np.arange(4)
y = np.ones(5)

print(x.shape)  # (4,)
print(y.shape)  # (5,)

print(x + y)
# ValueError: operands could not be broadcast together with shapes (4,) (5,) 

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [25]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x + 1
print(y)
print(np.add(x, 1))
# [2 3 4 5 6 7 8 9]

[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [8]:
y = x - 1
print(y)
print(np.subtract(x, 1))
# [0 1 2 3 4 5 6 7]

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [9]:
y = x * 2
print(y)
print(np.multiply(x, 2))
# [ 2  4  6  8 10 12 14 16]

[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]


In [23]:
y = x / 2
print(y)
print(np.divide(x, 2))
# [0.5 1.  1.5 2.  2.5 3.  3.5 4. ]

[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]


In [26]:
y = x % 3
print(y)
print(np.mod(x,3))

[1 2 0 1 2 0 1 2]
[1 2 0 1 2 0 1 2]


In [11]:
y = x ** 2
print(y)
print(np.power(x, 2))
# [ 1  4  9 16 25 36 49 64]

[ 1  4  9 16 25 36 49 64]
[ 1  4  9 16 25 36 49 64]


In [13]:
x = np.arange(1, 5)
print(x)  # [1 2 3 4]

y = np.sqrt(x)
print(y)
# [1.         1.41421356 1.73205081 2.        ]
print(np.power(x,0.5))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]


In [22]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.arange(1,6)
print(y)

z = x + y
print(z)
print(np.add(x,y))

z = x % y
print(z)
print(np.mod(x,y))

[1 2 3 4 5]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[0 0 1 2 0]
 [0 1 0 3 0]
 [0 0 2 0 0]
 [0 1 1 1 0]
 [0 0 0 2 0]]
[[0 0 1 2 0]
 [0 1 0 3 0]
 [0 0 2 0 0]
 [0 1 1 1 0]
 [0 0 0 2 0]]


In [15]:
z = x - y
print(z)
print(np.subtract(x, y))
# [[10 10 10 10 10]
#  [15 15 15 15 15]
#  [20 20 20 20 20]
#  [25 25 25 25 25]
#  [30 30 30 30 30]]

z = x * y
print(z)
print(np.multiply(x, y))
# [[ 11  24  39  56  75]
#  [ 16  34  54  76 100]
#  [ 21  44  69  96 125]
#  [ 26  54  84 116 150]
#  [ 31  64  99 136 175]]

z = x / y
print(z)
print(np.divide(x, y))
# [[11.          6.          4.33333333  3.5         3.        ]
#  [16.          8.5         6.          4.75        4.        ]
#  [21.         11.          7.66666667  6.          5.        ]
#  [26.         13.5         9.33333333  7.25        6.        ]
#  [31.         16.         11.          8.5         7.        ]]

z = x // y
print(z)
print(np.floor_divide(x, y))
# [[11  6  4  3  3]
#  [16  8  6  4  4]
#  [21 11  7  6  5]
#  [26 13  9  7  6]
#  [31 16 11  8  7]]

z = x ** np.full([1, 5], 2)
print(z)
print(np.power(x, np.full([5, 5], 2)))
# [[ 121  144  169  196  225]
#  [ 256  289  324  361  400]
#  [ 441  484  529  576  625]
#  [ 676  729  784  841  900]
#  [ 961 1024 1089 1156 1225]]

[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16.         11.          8.5         7.        ]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16. 

In [16]:
x = np.linspace(start=0, stop=np.pi / 2, num=10)
print(x)
# [0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
#  1.04719755 1.22173048 1.3962634  1.57079633]

y = np.sin(x)
print(y)
# [0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
#  0.8660254  0.93969262 0.98480775 1.        ]

z = np.arcsin(y)
print(z)
# [0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
#  1.04719755 1.22173048 1.3962634  1.57079633]

y = np.cos(x)
print(y)
# [1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
#  7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
#  1.73648178e-01 6.12323400e-17]

z = np.arccos(y)
print(z)
# [0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
#  1.04719755 1.22173048 1.3962634  1.57079633]

y = np.tan(x)
print(y)
# [0.00000000e+00 1.76326981e-01 3.63970234e-01 5.77350269e-01
#  8.39099631e-01 1.19175359e+00 1.73205081e+00 2.74747742e+00
#  5.67128182e+00 1.63312394e+16]

z = np.arctan(y)
print(z)
# [0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
#  1.04719755 1.22173048 1.3962634  1.57079633]

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
 7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
 1.73648178e-01 6.12323400e-17]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.00000000e+00 1.76326981e-01 3.63970234e-01 5.77350269e-01
 8.39099631e-01 1.19175359e+00 1.73205081e+00 2.74747742e+00
 5.67128182e+00 1.63312394e+16]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


In [17]:
x = np.arange(1, 5)
print(x)
# [1 2 3 4]
y = np.exp(x)
print(y)
# [ 2.71828183  7.3890561  20.08553692 54.59815003]
z = np.log(y)
print(z)
# [1. 2. 3. 4.]


[1 2 3 4]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


In [18]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.sum(x)
print(y)  # 575

y = np.sum(x, axis=0)
print(y)  # [105 110 115 120 125]

y = np.sum(x, axis=1)
print(y)  # [ 65  90 115 140 165]


575
[105 110 115 120 125]
[ 65  90 115 140 165]


In [27]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.cumsum(x)
print(y)
# [ 11  23  36  50  65  81  98 116 135 155 176 198 221 245 270 296 323 351
#  380 410 441 473 506 540 575]

y = np.cumsum(x, axis=0)
print(y)
# [[ 11  12  13  14  15]
#  [ 27  29  31  33  35]
#  [ 48  51  54  57  60]
#  [ 74  78  82  86  90]
#  [105 110 115 120 125]]

y = np.cumsum(x, axis=1)
print(y)
# [[ 11  23  36  50  65]
#  [ 16  33  51  70  90]
#  [ 21  43  66  90 115]
#  [ 26  53  81 110 140]
#  [ 31  63  96 130 165]]


[ 11  23  36  50  65  81  98 116 135 155 176 198 221 245 270 296 323 351
 380 410 441 473 506 540 575]
[[ 11  12  13  14  15]
 [ 27  29  31  33  35]
 [ 48  51  54  57  60]
 [ 74  78  82  86  90]
 [105 110 115 120 125]]
[[ 11  23  36  50  65]
 [ 16  33  51  70  90]
 [ 21  43  66  90 115]
 [ 26  53  81 110 140]
 [ 31  63  96 130 165]]


In [28]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.prod(x)
print(y)  # 788529152

y = np.prod(x, axis=0)
print(y)
# [2978976 3877632 4972968 6294624 7875000]

y = np.prod(x, axis=1)
print(y)
# [  360360  1860480  6375600 17100720 38955840]


3712525927079477248
[2978976 3877632 4972968 6294624 7875000]
[  360360  1860480  6375600 17100720 38955840]


In [29]:
y = np.cumprod(x)
print(y)
# [         11         132        1716       24024      360360     5765760
#     98017920  1764322560  -837609728   427674624   391232512    17180672
#    395155456   893796352   870072320  1147043840   905412608  -418250752
#    755630080  1194065920 -1638662144  -897581056   444596224 -2063597568
#    788529152]

y = np.cumprod(x, axis=0)
print(y)
# [[     11      12      13      14      15]
#  [    176     204     234     266     300]
#  [   3696    4488    5382    6384    7500]
#  [  96096  121176  150696  185136  225000]
#  [2978976 3877632 4972968 6294624 7875000]]

y = np.cumprod(x, axis=1)
print(y)
# [[      11      132     1716    24024   360360]
#  [      16      272     4896    93024  1860480]
#  [      21      462    10626   255024  6375600]
#  [      26      702    19656   570024 17100720]
#  [      31      992    32736  1113024 38955840]]

[                  11                  132                 1716
                24024               360360              5765760
             98017920           1764322560          33522128640
         670442572800       14079294028800      309744468633600
     7124122778572800   170978946685747200  4274473667143680000
   455850903478370304 -6138769679793553408 -5864854370833530880
 -4060080090786430976  7324805792373932032  5708050679077273600
 -1809819006622760960 -4383794997422456832 -1475077322687119360
  3712525927079477248]
[[     11      12      13      14      15]
 [    176     204     234     266     300]
 [   3696    4488    5382    6384    7500]
 [  96096  121176  150696  185136  225000]
 [2978976 3877632 4972968 6294624 7875000]]
[[      11      132     1716    24024   360360]
 [      16      272     4896    93024  1860480]
 [      21      462    10626   255024  6375600]
 [      26      702    19656   570024 17100720]
 [      31      992    32736  1113024 38955840]]


In [30]:
A = np.arange(2, 14).reshape((3, 4))
A[1, 1] = 8
print(A)
# [[ 2  3  4  5]
#  [ 6  8  8  9]
#  [10 11 12 13]]
print(np.diff(A))
# [[1 1 1]
#  [2 0 1]
#  [1 1 1]]
print(np.diff(A, axis=0))
# [[4 5 4 4]
#  [4 3 4 4]]

[[ 2  3  4  5]
 [ 6  8  8  9]
 [10 11 12 13]]
[[1 1 1]
 [2 0 1]
 [1 1 1]]
[[4 5 4 4]
 [4 3 4 4]]


In [31]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.clip(x, a_min=20, a_max=30)
print(y)
# [[20 20 20 20 20]
#  [20 20 20 20 20]
#  [21 22 23 24 25]
#  [26 27 28 29 30]
#  [30 30 30 30 30]]

[[20 20 20 20 20]
 [20 20 20 20 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [30 30 30 30 30]]


In [32]:
print(np.logical_not(3))  
# False
print(np.logical_not([True, False, 0, 1]))
# [False  True  True False]

x = np.arange(5)
print(np.logical_not(x < 3))
# [False False False  True  True]

print(np.logical_and(True, False))  
# False
print(np.logical_and([True, False], [True, False]))
# [ True False]
print(np.logical_and(x > 1, x < 4))
# [False False  True  True False]

print(np.logical_or(True, False))
# True
print(np.logical_or([True, False], [False, False]))
# [ True False]
print(np.logical_or(x < 1, x > 3))
# [ True False False False  True]

print(np.logical_xor(True, False))
# True
print(np.logical_xor([True, True, False, False], [True, False, True, False]))
# [False  True  True False]
print(np.logical_xor(x < 1, x > 3))
# [ True False False False  True]
print(np.logical_xor(0, np.eye(2)))
# [[ True False]
#  [False  True]]

False
[False  True  True False]
[False False False  True  True]
False
[ True False]
[False False  True  True False]
True
[ True False]
[ True False False False  True]
True
[False  True  True False]
[ True False False False  True]
[[ True False]
 [False  True]]
